### ISSUE TITLE
'cannot have an empty name.' 

### ISSUE THREAD

**Issue by ricardocanelas** [Jeroen-G/laravel-packager#3]
*laravel 5.0

After install..

php artisan

[LogicException]
The command defined in "JeroenG\Packager\PackagerNewCommand" cannot have an empty name.

**Comment by Jeroen-G** [comment]
That is because Laravel 5.1 changed the way console commands are executed (a signature instead of a name).
You'd think a x.1 version wouldn't break stuff, but apparently it did here.
The easiest way is to update to Laravel 5.1, which is also recommended since it is the version that is supported for the next few years.

**Comment by venty** [comment]
Upgrading did the trick. Thx :)

**Comment by Jeroen-G** [comment]
You're welcome. Nice to know other people use my package :smile:

**Comment by ekontiki89** [comment]
then i can not use your package on laravel 5.0?

**Comment by Jeroen-G** [comment]
I don't think so.
