### ISSUE TITLE
After removing package my project is broken

### ISSUE THREAD

**Issue by kornerson** [Jeroen-G/laravel-packager#67]
I installed this package and stared developing a package. Later on I decided I didn't want it, so I removed the package using "composer remove". I then realized I had the package files still on the project, so I simply deleted them. I also checked that there were no references to the package in config/app.php and also in composer.json

now "php artisan" command doesn't work. It returns this error:
"In ProviderRepository.php line 208:

  Class 'Vendor\Package\PackageServiceProvider' not found"

Nothing works. Searched EVERYWHERE in the project trying to find any string with any resemblance to the package name, nothing. Cleared caches from everything. Reinstalled Composer. And nothing....

It seem's there's a reference to this package somewhere outside the project, but I can't find where. 

If I don't find a solution I might need to restart the whole project as composer and artisan doesn't work at all.

**Comment by Jeroen-G** [comment]
Hi there!

`php artisan packager:remove` would have been better, `composer remove` doesn't do anything here.

If the issue is that the app cannot find the package service provider, then a reference to that provider is either still in config/app.php (not likely, since you already checked there) or the cache/autoloads. Have you tried `composer dump'? Because that is also the last step of [the remove command](https://github.com/Jeroen-G/laravel-packager/blob/master/src/Commands/RemovePackage.php).
