### ISSUE TITLE
Feature: ability to generate a package for Laravel Nova

### ISSUE THREAD

**Issue by 4n70w4** [Jeroen-G/laravel-packager#81]
https://nova.laravel.com/

It will be necessary to add several directories and classes. If interested, I will tell more.

**Comment by Jeroen-G** [comment]
This should be very doable with a skeleton such as [this one](https://github.com/Jeroen-G/packager-skeleton)!
The skeleton can be set in the config file and the `packager:new` command will fetch that when creating a new package.

**Comment by rjksn** [comment]
Laravel Nova has their own boilerplate if you weren't aware. Check out the customization docs, here's the [Defining Tools](https://nova.laravel.com/docs/2.0/customization/tools.html#defining-tools). 

    php artisan nova:tool acme/price-tracker

However I don't think it's possible to do the same with laravel-packager due to the limited/hardcoded Wrapping::fill() directory structure—you can't replace package names in `resources/js/field.js` for instance. I'm wondering how to solve this issue, either through adding a default file `replaceRules.php` or some recursive function (Nova is explicit with their renames and replaces).

    class Wrapping
    {
        public function fill($path)
        {
            $templates = array_merge(
                glob($path.'/composer.json'),
                glob($path.'/*.md'),
                glob($path.'/*.php'),
                glob($path.'/src/*.php'),
                glob($path.'/src/Facades/*.php'),
                glob($path.'/tests/*.php'),
                glob($path.'/config/*.php')
            );
            foreach ($templates as $file) {
                $this->fillInFile($file);
            }
        }
    }

**Comment by Jeroen-G** [comment]
I'm happy to accomodate for more flexible filling of (custom) skeletons!
